{{- if and .Values.gpuMetrics .Values.gpuMetrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bridge-data-exporter.name" . }}-gpu-inventory
  labels:
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bridge-data-exporter.name" . }}-gpu-inventory
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-rightsizing.bridgeDataExporterServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
