{{- $jvmEnabled := default false (and .Values.jvmMetrics .Values.jvmMetrics.enabled) }}
{{- $gpuEnabled := default false (and .Values.gpuMetrics .Values.gpuMetrics.enabled) }}
{{- if or $jvmEnabled $gpuEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
  name: {{ include "pod-rightsizing.bridgeDataExporterServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
