{{- if and .Values.jvmMetrics .Values.jvmMetrics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pilot
  name: {{ include "pod-rightsizing.bridgeDataExporterServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
