apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-custom-recording-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
data:
  custom-rules.yaml: |
{{ .Files.Get "files/custom-vm-recording-rules.yaml" | indent 4 }}
