apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoriametrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
      - name: victoriametrics
        image: victoriametrics/victoria-metrics:v1.112.0
        args:
        - -retentionPeriod=1w
        - -storageDataPath=/victoria-metrics-data
        - -search.maxStalenessInterval=5m
        - -search.minStalenessInterval=30s
        - -search.maxQueryDuration=2m
        - -search.disableCache
        - -memory.allowedPercent=60
        - -dedup.minScrapeInterval=30s
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: vm-data
          mountPath: /victoria-metrics-data
        {{- if .Values.victoriaMetrics.resources }}
        resources:
          {{- if .Values.victoriaMetrics.resources.requests }}
          requests:
            memory: {{ .Values.victoriaMetrics.resources.requests.memory }}
            cpu: {{ .Values.victoriaMetrics.resources.requests.cpu }}
          {{- end }}
          {{- if .Values.victoriaMetrics.resources.limits }}
          limits:
            memory: {{ .Values.victoriaMetrics.resources.limits.memory }}
            cpu: {{ .Values.victoriaMetrics.resources.limits.cpu }}
          {{- end }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: vm-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.victoriaMetrics.storageClassName | default "ebs-sc" }}
      resources:
        requests:
          storage: {{ .Values.victoriaMetrics.volumeSize | default "30Gi" }}

