apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoriametrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: victoriametrics
    {{- include "pod-rightsizing.labels" . | nindent 4 }} # Don't change this, since the component monitor uses labels from here to identify the component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
      - name: victoriametrics
        image: victoriametrics/victoria-metrics:v1.112.0
        args:
        - -retentionPeriod=1w
        - -storageDataPath=/victoria-metrics-data
        - -search.maxStalenessInterval=5m
        - -search.minStalenessInterval=30s
        - -search.maxQueryDuration=2m
        - -search.disableCache
        - -memory.allowedPercent=60
        - -dedup.minScrapeInterval=30s
        ports:
        - containerPort: 8428
        volumeMounts:
        - name: vm-data
          mountPath: /victoria-metrics-data
        {{- if .Values.victoriaMetrics.resources }}
        resources:
{{ .Values.victoriaMetrics.resources | toYaml | nindent 10 }}
        {{- end }}
      - name: vmalert
        image: "victoriametrics/vmalert:v1.112.0"
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        args:
        - -datasource.url=http://localhost:8428/
        - -remoteRead.url=http://localhost:8428/ # For vmalert to query data for rules
        - -remoteWrite.url=http://localhost:8428/ # For vmalert to write recording rule results and alerts
        - -rule=/etc/victoriametrics/rules/*.yaml # Glob pattern for rule files
        - -evaluationInterval={{ include "vmagent.scrapeInterval" . }}
        ports:
        - name: vmalert-http
          containerPort: 8880 # Default vmalert HTTP port
        volumeMounts:
        - name: recording-rules-volume
          mountPath: /etc/victoriametrics/rules
          readOnly: true
        {{- if .Values.victoriaMetrics.vmalert.resources }}
        resources:
{{ .Values.victoriaMetrics.vmalert.resources | toYaml | nindent 10 }}
        {{- end }}
      volumes:
        - name: recording-rules-volume
          configMap:
            name: vm-custom-recording-rules
  volumeClaimTemplates:
  - metadata:
      name: vm-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.victoriaMetrics.storageClassName | default "ebs-sc" }}
      resources:
        requests:
          storage: {{ .Values.victoriaMetrics.volumeSize | default "30Gi" }}

