apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendations-maker.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "recommendations-maker.name" . }}
  ports:
  - name: http
    port: {{ .Values.recommendationsMaker.port }}
    targetPort: {{ .Values.recommendationsMaker.port }}