apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: "{{ .Release.Namespace }}"
type: Opaque
{{- $config := get .Values "config" | default dict }}
{{- $customReplicaAggregationMethods := get $config "customReplicaAggregationMethods" | default dict }}
{{- $customReplicaCpuAggregationMethods := get $customReplicaAggregationMethods "cpu" | default dict }}
{{- $customReplicaMemoryAggregationMethods := get $customReplicaAggregationMethods "memory" | default dict }}
{{- $customReplicaAggregationMethodsData := dict }}
{{- $customReplicaCpuAggregationMethodsData := dict }}
{{- $customReplicaMemoryAggregationMethodsData := dict }}
{{- if hasKey $customReplicaCpuAggregationMethods "custom1" }}
{{- $_ := set $customReplicaCpuAggregationMethodsData "custom1" (int (get $customReplicaCpuAggregationMethods "custom1")) }}
{{- end }}
{{- if hasKey $customReplicaCpuAggregationMethods "custom2" }}
{{- $_ := set $customReplicaCpuAggregationMethodsData "custom2" (int (get $customReplicaCpuAggregationMethods "custom2")) }}
{{- end }}
{{- if gt (len $customReplicaCpuAggregationMethodsData) 0 }}
{{- $_ := set $customReplicaAggregationMethodsData "cpu" $customReplicaCpuAggregationMethodsData }}
{{- end }}
{{- if hasKey $customReplicaMemoryAggregationMethods "custom1" }}
{{- $_ := set $customReplicaMemoryAggregationMethodsData "custom1" (int (get $customReplicaMemoryAggregationMethods "custom1")) }}
{{- end }}
{{- if hasKey $customReplicaMemoryAggregationMethods "custom2" }}
{{- $_ := set $customReplicaMemoryAggregationMethodsData "custom2" (int (get $customReplicaMemoryAggregationMethods "custom2")) }}
{{- end }}
{{- if gt (len $customReplicaMemoryAggregationMethodsData) 0 }}
{{- $_ := set $customReplicaAggregationMethodsData "memory" $customReplicaMemoryAggregationMethodsData }}
{{- end }}
stringData:
  additionalSupportedKinds: |
{{- toYaml .Values.additionalSupportedKinds | nindent 4 }}
  customReplicaAggregationMethods: |
{{- if gt (len $customReplicaAggregationMethodsData) 0 }}
{{- toYaml $customReplicaAggregationMethodsData | nindent 4 }}
{{- else }}
    {}
{{- end }}
