{{- if and .Values.grafana.enabled .Values.grafana.deployDataSource}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-grafana-datasource
  labels:
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://victoriametrics.{{ .Release.Namespace }}:8428
      access: proxy
      isDefault: true
      editable: false
{{- end }}