apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kompass-pod-rightsizing-config.name" . }}
  namespace: {{ .Release.Namespace }}
data:
    recommendationsInterval: {{ (.Values.config).recommendationsInterval | default "30m" | quote }}
    cooldownBetweenActions: {{ (.Values.config).cooldownBetweenActions | default "2m" | quote }}
    hpaLookbackPeriod: {{ (.Values.config).hpaLookbackPeriod | default "3m" | quote }}
    bypassHpaVpaConflictValidator: {{ (.Values.config).bypassHpaVpaConflictValidator | default "true" | quote }}

    hpaThresholdCpuLimit: {{ (.Values.config).hpaThresholdCpuLimit | default "0.9" | quote }}
    hpaThresholdCpuRequest: {{ (.Values.config).hpaThresholdCpuRequest | default "1.1" | quote }}
    hpaThresholdMemoryLimit: {{ (.Values.config).hpaThresholdMemoryLimit | default "0.8" | quote }}
    hpaThresholdMemoryRequest: {{ (.Values.config).hpaThresholdMemoryRequest | default "1" | quote }}

    hpaMaxValue: {{ (.Values.config).hpaMaxValue | default "200" | quote }}
    hpaMinValue: {{ (.Values.config).hpaMinValue | default "70" | quote }}

    failedActionRetriesAmount: {{ (.Values.config).failedActionRetriesAmount | default "1" | quote }}

    resourceIdsQueryChunkSize: {{ (.Values.config).resourceIdsQueryChunkSize | default "30" | quote }}
    
    builtinPolicies: |
{{ toYaml .Values.config.builtinPolicies | indent 6 }}

    throttlingRollbackTimeRange: |
{{- if and .Values.config (.Values.config).throttlingRollbackTimeRange }}
{{ (.Values.config).throttlingRollbackTimeRange | nindent 6 }}
{{- else }}
      from: "20m"
      to: "120m"
{{- end }}
