apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: {{ .Release.Namespace }}
  labels:
    app: vmagent
    {{- include "pod-rightsizing.labels" . | nindent 4 }} # Don't change this, since the component monitor uses labels from here to identify the component
spec:
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      serviceAccountName: vmagent
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:v1.112.0
        args:
          - -promscrape.config=/etc/vmagent-config/vmagent-config.yaml
          - -remoteWrite.url=http://victoriametrics.{{ .Release.Namespace }}:8428/api/v1/write
        ports:
        - containerPort: 8429
        volumeMounts:
        - name: config
          mountPath: /etc/vmagent-config
      volumes:
      - name: config
        configMap:
          name: vmagent-config
        # Optional: Mount kubelet certificates if needed for secure scraping
