{{- $actionTakerPodSecurityContext := include "pod-rightsizing.securityContext.pod" (dict "root" . "componentSecurityContext" .Values.actionTaker.podSecurityContext) | fromYaml }}
{{- $actionTakerSecurityContext := include "pod-rightsizing.securityContext.container" (dict "root" . "componentSecurityContext" .Values.actionTaker.securityContext) | fromYaml }}
{{- $actionTakerKubeRbacProxySecurityContext := include "pod-rightsizing.securityContext.actionTakerKubeRbacProxy" (dict "root" . "actionTakerSecurityContext" .Values.actionTaker.securityContext "kubeRbacProxySecurityContext" .Values.actionTaker.kubeRbacProxy.securityContext) | fromYaml }}
{{- $actionTakerPodLabels := include "pod-rightsizing.podTemplateLabels" (dict "root" . "componentValues" .Values.actionTaker) | fromYaml }}
{{- $actionTakerPodAnnotations := include "pod-rightsizing.podTemplateAnnotations" (dict "root" . "componentValues" .Values.actionTaker) | fromYaml }}
{{- $actionTakerDefaultAffinity := include "pod-rightsizing.actionTaker.defaultAffinity" . | fromYaml }}
{{- $actionTakerAffinity := include "pod-rightsizing.affinity" (dict "root" . "componentValues" .Values.actionTaker "baseAffinity" $actionTakerDefaultAffinity) | fromYaml }}
{{- $actionTakerImagePullSecrets := include "pod-rightsizing.imagePullSecrets" (dict "root" . "componentValues" .Values.actionTaker) | fromYamlArray }}
{{- $actionTakerTopologySpreadConstraints := include "pod-rightsizing.topologySpreadConstraints" (dict "root" . "componentValues" .Values.actionTaker) | fromYamlArray }}
{{- $actionTakerAutomountServiceAccountToken := include "pod-rightsizing.automountServiceAccountToken" (dict "root" . "componentValues" .Values.actionTaker) }}
{{- $actionTakerRuntimeClassName := include "pod-rightsizing.runtimeClassName" (dict "root" . "componentValues" .Values.actionTaker) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    {{- include "pod-rightsizing.labels" . | nindent 4 }} # Don't change this, since the component monitor uses labels from here to identify the component
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "action-taker.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.actionTaker.replicaCount | default 1 }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: pod-rightsizing
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: action-taker
        {{- with $actionTakerPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: pod-rightsizing
        {{- with $actionTakerPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.actionTaker.priorityClassName }}
      priorityClassName: {{ .Values.actionTaker.priorityClassName }}
      {{- end }}
      {{- if $actionTakerRuntimeClassName }}
      runtimeClassName: {{ $actionTakerRuntimeClassName }}
      {{- end }}
      {{- with $actionTakerImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $actionTakerTopologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- with $actionTakerAffinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kube-rbac-proxy
          image: {{ .Values.actionTaker.kubeRbacProxy.image.registry }}/{{ .Values.actionTaker.kubeRbacProxy.image.repository }}:{{ .Values.actionTaker.kubeRbacProxy.image.tag }}
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          {{- with $actionTakerKubeRbacProxySecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ .Values.actionTaker.name }}
          image: {{ .Values.registry }}{{ .Values.actionTaker.image.name }}:{{ .Values.actionTaker.image.tag | default .Chart.AppVersion }}
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
            - --releaseNamespace={{ .Release.Namespace }}
            - --configMapName={{ include "kompass-pod-rightsizing-config.name" . }}
            - --server-port={{ .Values.actionTaker.serverPort }}
            - --image-tag={{ .Values.actionTaker.image.tag }}
            - --rightsizing-enabled={{ .Values.enabled }}
            {{- if .Values.actionTaker.image.args }}
            {{- range .Values.actionTaker.image.args }}
            - {{ . }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: {{ .Values.actionTaker.serverPort }}
              name: http-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: webhook-certs
              readOnly: true
          command:
            - /action-taker
          env:
            {{- if eq .Values.actionTaker.enableWebhooks false }}
            - name: ENABLE_WEBHOOKS
              value: "false"
            {{- end }}
            {{- if eq .Values.actionTaker.syncBuiltinPolicies false }}
            - name: SYNC_BUILTIN_POLICIES
              value: "false"
            {{- end }}
            - name: ENABLE_APPLICATION_WEBHOOK
              value: {{ .Values.actionTaker.webhooks.application.enabled | quote }}
            - name: CM_NAME
              value: {{ include "kompass-pod-rightsizing-config.name" . }}
            - name: INITIAL_VALUES_CM_NAME
              value: {{ include "kompass-pod-rightsizing-initial-values-config.name" . }}
            - name: CM_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: CONTAINER_NAME
              value: {{ .Values.actionTaker.name }}
            - name: VM_URL
              value: {{ include "pod-rightsizing.victoriaMetrics.url" . }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if and .Values.global.cxLogging .Values.global.cxLogging.enabled }}
            - name: CX_API_KEY
              value: {{ .Values.global.cxLogging.apiKey }}
            - name: CX_CLUSTER_NAME
              value: {{ .Values.global.cxLogging.clusterName }}
            - name: CORALOGIX_METRICS_URL
              value: {{ .Values.global.cxLogging.metricsUrl }}
            - name: CORALOGIX_INGRESS_URL
              value: {{ .Values.global.cxLogging.ingressUrl }}
            {{- else if and .Values.cxLogging .Values.cxLogging.enabled }}
            - name: CX_API_KEY
              value: {{ .Values.cxLogging.apiKey }}
            - name: CX_CLUSTER_NAME
              value: {{ .Values.cxLogging.clusterName }}
            - name: CORALOGIX_METRICS_URL
              value: {{ .Values.cxLogging.metricsUrl }}
            - name: CORALOGIX_INGRESS_URL
              value: {{ .Values.cxLogging.ingressUrl }}
            {{- end }}
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: RIGHTSIZING_SECRET_NAME
              value: {{ .Values.secret }}
            {{- if .Values.actionTaker.env }}
            {{- range .Values.actionTaker.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- include "pod-rightsizing.actionTaker.resources" . | nindent 10 }}
          {{- with $actionTakerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: kompass-pod-rightsizing-webhook-cert
      {{- with $actionTakerPodSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-rightsizing.serviceAccountName" . }}
      {{- if ne $actionTakerAutomountServiceAccountToken "" }}
      automountServiceAccountToken: {{ $actionTakerAutomountServiceAccountToken }}
      {{- end }}
      terminationGracePeriodSeconds: 10