apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pilot
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "pod-rightsizing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
