apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
{{- if .Values.rightsizing.orderedCertificateCreation }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
{{- end }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kompass-pod-rightsizing-webhook-cert
  namespace: {{ .Release.Namespace }}  # Ensure it's deployed in the correct namespace
  annotations:
{{- if .Values.rightsizing.orderedCertificateCreation }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
{{- end }}
    cert-manager.io/disable-name-generation: "true"
  labels:
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
spec:
  secretName: kompass-pod-rightsizing-webhook-cert
  dnsNames:
    - {{ include "kompass-webhook-svc.name" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kompass-webhook-svc.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer