apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: victoriametrics
  ports:
  - name: http
    port: 8428
    targetPort: 8428