{
 "title": "Horizontal Scaling Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kube_namespace_status_phase{phase=\"Active\"})"
    }
   },
   {
    "name": "workload_name",
    "label": "Workload Name",
    "query": {
     "query": "query_result(sort(label_replace(kube_deployment_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"deployment\", \"(.+)\") or label_replace(kube_statefulset_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"statefulset\", \"(.+)\") or label_replace(kube_daemonset_metadata_generation{namespace=\"$namespace\"}, \"name\", \"$1\", \"daemonset\", \"(.+)\")))"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(kube_pod_container_info{namespace=\"$namespace\"} * on(pod) group_left(created_by_name) kompass_pod_info{created_by_name=\"$workload_name\", namespace=\"$namespace\"})"
    }
   },
   { "name": "recommendation_mode", "label": "Recommendation Mode", "query": "variants,live" },
   { "name": "bytes_to_gb", "label": "bytes_to_gb", "query": "1024 / 1024 / 1024" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": " min(last_over_time(\n    (\n      (\n        kube_pod_container_resource_requests{\n          container=\"$container\",resource=\"cpu\"\n        }\n          * on(namespace,pod) group_left(workload_name,workload_kind)\n        kompass_pod_info{\n          created_by_name=\"$workload_name\",\n          namespace=\"$namespace\"\n        }\n      )\n        * on(namespace,workload_name,workload_kind) group_left()\n      max(\n        kompass_rs_recommendations{\n          resource_type=\"hpa_min_replica\",\n          workload_name=\"$workload_name\",\n          namespace=\"$namespace\",\n          resource_source=\"desired\",\n          mode=\"$recommendation_mode\"\n        }\n      ) by(namespace,workload_name,workload_kind)\n    )[30m:])\n) by(namespace,workload_name,workload_kind)",
     "legendFormat": "Desired Requests At Min Replica Count"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": " sum by (namespace, container)(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$container\"}) / $bytes_to_gb",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "sum by (namespace, container)(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$container\"}) / $bytes_to_gb",
     "legendFormat": "Total Requests"
    },
    {
     "expr": " min(last_over_time(\n    (\n      (\n        kube_pod_container_resource_requests{\n          container=\"$container\",resource=\"memory\"\n        }\n          * on(namespace,pod) group_left(workload_name,workload_kind)\n        kompass_pod_info{\n          created_by_name=\"$workload_name\",\n          namespace=\"$namespace\"\n        }\n      )\n        * on(namespace,workload_name,workload_kind) group_left()\n      max(\n        kompass_rs_recommendations{\n          resource_type=\"hpa_min_replica\",\n          workload_name=\"$workload_name\",\n          namespace=\"$namespace\",\n          resource_source=\"desired\",\n          mode=\"$recommendation_mode\"\n        }\n      ) by(namespace,workload_name,workload_kind)\n    )[30m:])\n) by(namespace,workload_name,workload_kind) / $bytes_to_gb",
     "legendFormat": "Desired Requests At Min Replica Count"
    }
   ]
  },
  {
   "title": "Replicas Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"$container\", namespace=\"$namespace\"} * on (namespace, pod, container) group_left(workload_name) kompass_pod_info{workload_name=\"$workload_name\"})",
     "legendFormat": "Current Replica Count"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\"}\n  * on (namespace, horizontalpodautoscaler)\n    group_left(scaletargetref_kind, scaletargetref_name)\n    kube_horizontalpodautoscaler_info{\n      namespace=\"$namespace\",\n      scaletargetref_kind=\"Deployment\",\n      scaletargetref_name=\"$workload_name\"\n    }\n ",
     "legendFormat": "Min Replica Count"
    }
   ]
  },
  {
   "title": "HPA Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA CPU"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"memory\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA Memory"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", resource_type=\"hpa_cpu\", mode=\"$recommendation_mode\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa CPU"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", resource_type=\"hpa_memory\", mode=\"$recommendation_mode\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa Memory"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (container, namespace, created_by_name, created_by_kind)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((delta(kube_pod_container_status_restarts_total{container=\"$container\", namespace=\"$namespace\"}[1m])  > 0) * on (pod, container, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", container=\"$container\", namespace=\"$namespace\"}  > 0) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}) by (container, pod, namespace, created_by_name, created_by_kind)) by (container, created_by_name, created_by_kind, namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audit table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", mode=\"$recommendation_mode\", namespace=\"$namespace\", container=\"$container\"}[$__range]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "kompass_rs_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}