{
 "title": "Pod-RightSizing Jobs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "strategy", "label": "strategy", "query": "Conservative, Default" },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_status_phase{phase=\"Active\"})"
    }
   },
   {
    "name": "workload_name",
    "label": "job group",
    "query": {
     "query": "query_result(max_over_time(max(kompass_pod_info{namespace=\"$namespace\",workload_kind=\"jobsgroup\"}) by (workload_name))[24h])"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "query_result(max_over_time(max(kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\" ,workload_kind=\"jobsgroup\"}) by (container))[24h])"
    }
   },
   { "name": "CpuCost", "query": "0.045" },
   { "name": "MemCost", "query": "0.011" },
   { "name": "GiB", "query": "(1024*1024*1024)" },
   { "name": "s_rate", "query": "15s" }
  ]
 },
 "panels": [
  {
   "title": "CPU Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(kompass_rs_recommendations{mode=\"variants\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"cpu\",strategy=~\"(?i)$strategy\",resource_source=\"desired\"}[1h])",
     "legendFormat": "recommendation for strategy"
    },
    {
     "expr": "(kompass_rs_recommendations{mode=\"live\",type=\"orchestration\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"cpu\",resource_source=\"desired\"}[7d])",
     "legendFormat": "active recommendation"
    },
    {
     "expr": "kompass_container_cpu_usage_max_rate{namespace=\"$namespace\",container=\"$container\",created_by_kind=\"jobsgroup\",created_by_name=\"$workload_name\"}",
     "legendFormat": "max usage"
    }
   ]
  },
  {
   "title": "CPU Requests (Average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"cpu\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})",
     "legendFormat": "without rs"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"}\n* on (namespace,pod,container) group_left(workload_name) kompass_pod_info {namespace=\"$namespace\", workload_kind=\"jobsgroup\",workload_name=\"$workload_name\",container=\"$container\", status=\"running\"})",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "CPU Savings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(\nsum(\n((kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"cpu\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})\n- \non (mode,container,namespace,resource_type,workload_kind,workload_name,resource_id,strategy)\n(kompass_rs_recommendations{mode=\"active\",resource_source=\"desired\",container=\"$container\",namespace=\"$namespace\",resource_type=\"cpu\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"}))\n)\n/\non (mode,container,namespace,resource_type,workload_kind,workload_name,resource_id,strategy)\nsum((kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"cpu\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})),\n0)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "last_over_time(kompass_rs_recommendations{mode=\"variants\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"memory\",strategy=~\"(?i)$strategy\",resource_source=\"desired\"}[1h])/$GiB",
     "legendFormat": "recommendation for strategy"
    },
    {
     "expr": "(kompass_rs_recommendations{mode=\"live\",type=\"orchestration\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"memory\",resource_source=\"desired\"}[15s])/$GiB",
     "legendFormat": "active recommendation"
    },
    {
     "expr": "kompass_container_memory_usage_max{namespace=\"$namespace\",container=\"$container\",created_by_kind=\"jobsgroup\",created_by_name=\"$workload_name\"}/$GiB",
     "legendFormat": "max usage"
    }
   ]
  },
  {
   "title": "Memory Requests (Average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "avg(kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"memory\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})/$GiB",
     "legendFormat": "without rs"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"}\n* on (namespace,pod,container) group_left(workload_name) kompass_pod_info {namespace=\"$namespace\", workload_kind=\"jobsgroup\",workload_name=\"$workload_name\",container=\"$container\", status=\"running\"})/$GiB",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory Savings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(\nsum(\n((kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"memory\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})\n- \non (mode,container,namespace,resource_type,workload_kind,workload_name,resource_id,strategy)\n(kompass_rs_recommendations{mode=\"active\",resource_source=\"desired\",container=\"$container\",namespace=\"$namespace\",resource_type=\"memory\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"}))\n)\n/\non (mode,container,namespace,resource_type,workload_kind,workload_name,resource_id,strategy)\nsum((kompass_rs_recommendations{mode=\"active\",resource_source=\"current\",container=\"$container\",namespace=\"$namespace\",resource_type=\"memory\",workload_kind=\"job\",resource_id=\"$namespace;$workload_name;jobsgroup\"})),\n0)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count (\n    kompass_pod_info{namespace=\"$namespace\",workload_kind=\"jobsgroup\",workload_name=\"$workload_name\", container=\"$container\",status=\"running\"}\n)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (container, namespace, created_by_name, created_by_kind) > 0",
     "legendFormat": "{{created_by_name}} - Throttling"
    },
    {
     "expr": "sum((((delta( kube_pod_container_status_restarts_total{ container=\"$container\",namespace=\"$namespace\" }[1m]) > 0 ) * on(pod,container,namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=\"$container\",namespace=\"$namespace\"} > 0) ) or (kube_pod_container_status_terminated_reason{reason=\"OOMKilled\",container=\"$container\",namespace=\"$namespace\"} > 0) ) * on(namespace,container,pod) group_left(created_by_name,created_by_kind,namespace,resource_id) max( kompass_pod_info{ workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}) by(namespace,container,resource_id,created_by_name,created_by_kind,pod)) by(resource_id,container,created_by_name,created_by_kind,namespace)",
     "legendFormat": "{{created_by_name}} - OOM"
    }
   ]
  }
 ]
}