{
 "title": "Pod-RightSizing Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "workload_kind",
    "label": "Kind",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_kind!=\"virtualworkload\"},created_by_kind)"
    }
   },
   {
    "name": "workload_name",
    "label": "Workload",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_kind=\"$workload_kind\"},created_by_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_name=\"$workload_name\", created_by_kind=\"$workload_kind\"},container)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "balanced, cost-focused, stability-focused, all, none"
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kompass_container_cpu_usage_max_rate{container=\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\",created_by_kind=\"$workload_kind\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"live\",resource_source=\"desired\", workload_kind=\"$workload_kind\"}[15s:15s])[1d]",
     "legendFormat": "Desired"
    },
    {
     "expr": "avg((avg_over_time(avg(kube_pod_container_resource_requests{resource=\"cpu\", container=\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\", container=\"$container\", workload_kind=\"$workload_kind\"}) by (container)",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"balanced\"})[1d] * (\"$policy\" == 'balanced' or \"$policy\" == 'all')",
     "legendFormat": "Balanced Policy"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"cost-focused\"})[1d] * (\"$policy\" == 'cost-focused' or \"$policy\" == 'all')",
     "legendFormat": "Cost Focused Policy"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"cpu\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"stability-focused\"})[1d] * (\"$policy\" == 'stability-focused' or \"$policy\" == 'all')",
     "legendFormat": "Stability Focused Policy"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kompass_container_memory_usage_max{container=\"$container\", namespace=\"$namespace\", created_by_name=\"$workload_name\", created_by_kind=\"$workload_kind\" } / 1024 / 1024",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kompass_rs_recommendations{namespace=\"$namespace\", container=\"$container\", resource_type=\"memory\", mode=\"live\", resource_source=\"desired\", workload_name=\"$workload_name\", workload_kind=\"$workload_kind\"}[15s:15s])[1d] / 1024 / 1024",
     "legendFormat": "Desired"
    },
    {
     "expr": "avg((avg_over_time(avg(kube_pod_container_resource_requests{resource=\"memory\", container=\"$container\", namespace=\"$namespace\"}) by(pod, namespace, container, id))[5m]) * on(pod, namespace) group_left(owner_name) kompass_pod_info{namespace=\"$namespace\", workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\"}) by (container)  / 1024 / 1024",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"balanced\"})[1d] / 1024 / 1024 * (\"$policy\" == 'balanced' or \"$policy\" == 'all')",
     "legendFormat": "Balanced Policy"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"cost-focused\"})[1d] / 1024 / 1024 * (\"$policy\" == 'cost-focused' or \"$policy\" == 'all')",
     "legendFormat": "Cost Focused Policy"
    },
    {
     "expr": "avg(kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\", resource_type=\"memory\", mode=\"variants\",resource_source=\"desired\", rightsizing_policy=\"stability-focused\"})[1d] / 1024 / 1024 * (\"$policy\" == 'stability-focused' or \"$policy\" == 'all')",
     "legendFormat": "Stability Focused Policy"
    }
   ]
  },
  {
   "title": "Replicas Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"$container\", namespace=\"$namespace\"} * on (namespace, pod, container) group_left(workload_name) kompass_pod_info{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (container, namespace, created_by_name, created_by_kind)",
     "legendFormat": "Throttling"
    },
    {
     "expr": "sum((delta(kube_pod_container_status_restarts_total{container=\"$container\", namespace=\"$namespace\"}[1m])  > 0) * on (pod, container, namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", container=\"$container\", namespace=\"$namespace\"}  > 0) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(kompass_pod_info{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", container=\"$container\", namespace=\"$namespace\"}) by (container, pod, namespace, created_by_name, created_by_kind)) by (container, created_by_name, created_by_kind, namespace)",
     "legendFormat": "OOM"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA CPU"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"memory\", namespace=\"$namespace\"} * on (horizontalpodautoscaler) group_left () kube_horizontalpodautoscaler_info{scaletargetref_name=\"$workload_name\", namespace=\"$namespace\"}",
     "legendFormat": "HPA Memory"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_cpu\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa CPU"
    },
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", resource_type=\"hpa_memory\", mode=\"live\", workload_name=\"$workload_name\", resource_source=\"desired\", namespace=\"$namespace\"}",
     "legendFormat": "Desired Hpa Memory"
    }
   ]
  },
  {
   "title": "Audit table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kompass_rs_recommendations{workload_name=\"$workload_name\", workload_kind=\"$workload_kind\", mode=\"live\", namespace=\"$namespace\", container=\"$container\"}[$__range]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "kompass_rs_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}