{
 "title": "Pod-RightSizing Virtual Workloads Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "virtual_workload_type",
    "label": "Type",
    "query": {
     "query": "label_values(kompass_pod_info{namespace=\"$namespace\", workload_kind=\"virtualworkload\"},virtual_workload_type)"
    }
   },
   {
    "name": "workload_name",
    "label": "Workload",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_kind=\"virtualworkload\"},created_by_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kompass_container_cpu_usage_max_rate{namespace=\"$namespace\", created_by_name=\"$workload_name\", created_by_kind=\"virtualworkload\"},container)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "balanced, cost-focused, stability-focused"
   },
   { "name": "GiB", "query": "(1024*1024*1024)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(kompass_rs_recommendations{mode=\"variants\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"cpu\",rightsizing_policy=\"$policy\",resource_source=\"desired\"}[1h])",
     "legendFormat": "recommendation for policy"
    },
    {
     "expr": "(kompass_rs_recommendations{mode=\"live\",type=\"orchestration\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"cpu\",resource_source=\"desired\"}[7d])",
     "legendFormat": "active recommendation"
    },
    {
     "expr": "kompass_container_cpu_usage_max_rate{namespace=\"$namespace\",container=\"$container\",created_by_kind=\"virtualworkload\",created_by_name=\"$workload_name\"}",
     "legendFormat": "max usage"
    }
   ]
  },
  {
   "title": "CPU Requests (Average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "WITH (\n  baseline = max(last_over_time(\n    kompass_rs_recommendations{\n      mode=\"active\",\n      namespace=\"$namespace\",\n      resource_id=\"$namespace;$workload_name;virtualworkload\",\n      resource_source=\"current\",\n      resource_type=\"cpu\",\n      container=\"$container\"\n    }[7d]\n  )),\n  pod_count = count(count by (pod) (\n    kompass_pod_info{\n      namespace=\"$namespace\",\n      resource_id=\"$namespace;$workload_name;virtualworkload\",\n      container=\"$container\",\n      status=\"running\"\n    }\n  ))\n)\nbaseline * clamp_max(pod_count, 1)",
     "legendFormat": "without rs"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"cpu\"}\n* on (namespace,pod,container) group_left(workload_name) kompass_pod_info {namespace=\"$namespace\", workload_kind=\"virtualworkload\",workload_name=\"$workload_name\",container=\"$container\", status=\"running\"})",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "CPU Savings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "WITH (\n  rid = \"$namespace;$workload_name;virtualworkload\",\n\n  replica_initial_minus_desired = max by (pod, resource_id, resource_type) (\n    kompass_pod_info{status=\"running\", resource_id=rid}\n    * on(resource_id, pod) group_left(resource_type)\n      kompass_rs_initial_minus_desired{resource_id=rid, pod!=\"\", resource_type=\"cpu\"}\n  )\n)\n\nsum(replica_initial_minus_desired) by (resource_id)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Memory Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "last_over_time(kompass_rs_recommendations{mode=\"variants\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"memory\",rightsizing_policy=\"$policy\",resource_source=\"desired\"}[1h])/$GiB",
     "legendFormat": "recommendation for policy"
    },
    {
     "expr": "(kompass_rs_recommendations{mode=\"live\",type=\"orchestration\",namespace=\"$namespace\",workload_name=\"$workload_name\",container=\"$container\",resource_type=\"memory\",resource_source=\"desired\"}[7d])/$GiB",
     "legendFormat": "active recommendation"
    },
    {
     "expr": "kompass_container_memory_usage_max{namespace=\"$namespace\",container=\"$container\",created_by_kind=\"virtualworkload\",created_by_name=\"$workload_name\"}/$GiB",
     "legendFormat": "max usage"
    }
   ]
  },
  {
   "title": "Memory Requests (Average)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "WITH (\n  baseline_mem = max(\n    last_over_time(\n      kompass_rs_recommendations{\n        mode=\"active\",\n        namespace=\"$namespace\",\n        resource_id=\"$namespace;$workload_name;virtualworkload\",\n        resource_source=\"current\",\n        resource_type=\"memory\",\n        container=\"$container\"\n      }[7d]\n    )\n  ),\n\n  pod_count = count(\n    count by (pod) (\n      kompass_pod_info{\n        namespace=\"$namespace\",\n        resource_id=\"$namespace;$workload_name;virtualworkload\",\n        container=\"$container\",\n        status=\"running\"\n      }\n    )\n  )\n)\nbaseline_mem * clamp_max(pod_count, 1)/$GiB",
     "legendFormat": "without rs"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"$container\",resource=\"memory\"}\n* on (namespace,pod,container) group_left(workload_name) kompass_pod_info {namespace=\"$namespace\", workload_kind=\"virtualworkload\",workload_name=\"$workload_name\",container=\"$container\", status=\"running\"})/$GiB",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory Savings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "WITH (\n  rid = \"$namespace;$workload_name;virtualworkload\",\n\n  replica_initial_minus_desired = max by (pod, resource_id, resource_type) (\n    kompass_pod_info{status=\"running\", resource_id=rid}\n    * on(resource_id, pod) group_left(resource_type)\n      kompass_rs_initial_minus_desired{resource_id=rid, pod!=\"\", resource_type=\"memory\"}\n  )\n)\n\nsum(replica_initial_minus_desired) by (resource_id)",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count (\n    kompass_pod_info{namespace=\"$namespace\",workload_kind=\"virtualworkload\",workload_name=\"$workload_name\", container=\"$container\",status=\"running\"}\n)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Events (Throttling/OOM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_seconds_total{container=\"$container\", namespace=\"$namespace\"}[5m]) * on (container, pod, namespace) group_left (created_by_name, created_by_kind) max(max_over_time(kompass_pod_info{workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}[5m])) by (container, pod, created_by_name, created_by_kind, namespace)) by (container, namespace, created_by_name, created_by_kind) > 0",
     "legendFormat": "Throttling"
    },
    {
     "expr": "sum((((delta( kube_pod_container_status_restarts_total{ container=\"$container\",namespace=\"$namespace\" }[1m]) > 0 ) * on(pod,container,namespace) (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",container=\"$container\",namespace=\"$namespace\"} > 0) ) or (kube_pod_container_status_terminated_reason{reason=\"OOMKilled\",container=\"$container\",namespace=\"$namespace\"} > 0) ) * on(namespace,container,pod) group_left(created_by_name,created_by_kind,namespace,resource_id) max( kompass_pod_info{ workload_name=\"$workload_name\", container=\"$container\", namespace=\"$namespace\"}) by(namespace,container,resource_id,created_by_name,created_by_kind,pod)) by(resource_id,container,created_by_name,created_by_kind,namespace)",
     "legendFormat": "OOM"
    }
   ]
  }
 ]
}