apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pre-upgrade-crds
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
data:
  kompass.zesty.co_virtualworkloads.yaml: |
{{ .Files.Get "crds/kompass.zesty.co_virtualworkloads.yaml" | indent 4 }}
  rightsizing.kompass.zesty.co_actions.yaml: |
{{ .Files.Get "crds/rightsizing.kompass.zesty.co_actions.yaml" | indent 4 }}
  rightsizing.kompass.zesty.co_policies.yaml: |
{{ .Files.Get "crds/rightsizing.kompass.zesty.co_policies.yaml" | indent 4 }}
