{{- if .Values.guardian.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-rightsizing.guardianServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: guardian
    {{- include "pod-rightsizing.labels" . | nindent 4 }}
{{- end }}
