apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: {{ .Release.Namespace }}
data:
  vmagent-config.yaml: |
    scrape_configs:
      # For container CPU and memory metrics
      - job_name: 'kubelet'
        scrape_interval: 30s
        scheme: https
        tls_config:
          insecure_skip_verify: true
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node
          - target_label: __metrics_path__
            replacement: /metrics/cadvisor
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            target_label: __address__
            replacement: ${1}:10250
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: '.*'
            action: keep

      # for collecting Pilot metrics
      - job_name: 'pilot'
        scrape_interval: 30s
        static_configs:
          - targets: ['http://{{ include "recommendations-maker.name" . }}.{{ .Release.Namespace }}:{{ .Values.recommendationsMaker.port }}']

      # for collecting VM metrics
      - job_name: 'vmetrics'
        scrape_interval: 30s
        static_configs:
          - targets: ['http://victoriametrics.{{ .Release.Namespace }}:8428']

      # For pod and node metrics
      - job_name: 'kube-state-metrics'
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: pilot-kube-state-metrics
            action: keep
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: '.*'
            action: keep

      {{- if .Values.tests.enabled }}
      - job_name: locust_scrapper
        scrape_interval: 5s
        static_configs:
        - targets:
          - {{ .Release.Name }}-{{ .Values.tests.locust.exporter.name }}-svc.{{ .Release.Namespace }}:{{ .Values.tests.locust.exporter.port }}
      {{- end }}