name: Release Charts

on:
  push:
    branches:
      - main
      - helm-repo-setup

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        id: install

      - name: Add helm dependencies' repos
        run: |
          helm repo add kube-state-metrics https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add cert-manager https://charts.jetstack.io

      - name: Run helm release
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          pages_branch: main
          charts_dir: charts
          packages_with_index: true
